### ISSUE TITLE
Send GET request to server

### ISSUE THREAD

**Issue by LeeMPenney** [reisman-internship-2019-greenmap/GreenMap-app#28]

**Comment by LauraPenney** [comment]
To do:
Make a dummy express server that mimics the processing our server would do
Make relevant data be stored in the scanner component's state as strings
Append those strings to the URL that the server is running on

Basic flow:
```javascript
    _onScan({data}) {
        //code controlling for repeated calls to _onScan
        this.setState({barcodeData: data.toString()});
        //display loading animation
        fetch(`url/manual=0/data={this.state.barcodeData')
            .then(navigate-to-results-screen);
 ```

**Comment by ShekharDewan** [comment]
Fantastic, this sounds great! Thanks for looking into it already.

**Comment by LeeMPenney** [comment]
I ported the server team's code since their server was configured for cors, but still having the same issue. If the client makes a request to a live web address (e.g. http://example.com/movies.json) then it works fine. Best thing to do is look at the server that's live on Heroku, but I'm not clear on which url to use/how to find the live instance.

**Comment by LeeMPenney** [comment]
closing for now, will re-open this issue when we're ready to talk to the live server
