### ISSUE TITLE
Implement Redux and stackNavigator

### ISSUE THREAD

**Issue by LeeMPenney** [reisman-internship-2019-greenmap/GreenMap-app#29]
Aiming to build a skeleton of the functional side of the front-end so that we have good data and screen flow by the time we're ready to start making it pretty :)

**Comment by ShekharDewan** [comment]
Sounds good!

**Comment by LeeMPenney** [comment]
closing because redux and stackNavigator has been implemented. See issue #31 and #32 for planned next steps
