### ISSUE TITLE
Main Screen Prototype

### ISSUE THREAD

**Issue by LauraPenney** [reisman-internship-2019-greenmap/GreenMap-app#6]
Make a prototype for the screen users will see once they open our app. Should include a "Scan" button.

**Comment by LauraPenney** [comment]
I have one made but it's only an example and something we can build off of (or not use at all! It's just an idea).

**Comment by ShekharDewan** [comment]
I like the idea - for the app I'm thinking we should just default to the camera being open so its ready to scan. We can have a button/dropdown or other mechanism for other options.

**Comment by LauraPenney** [comment]
That'd be a good flow, yes! I'll aim to get some code going to make that happen
